Iphone X queries
OlegBaras/mogotex pull request #70
Opened 2021-01-22 22:21 UTC by OlegBaras

2021-01-23 01:17 UTC, aurimas-darguzis requested changes
few things to imrpove

2021-01-23 01:17 UTC, aurimas-darguzis commented on src/components/css/HeaderNav.css
> +  flex-grow: 1;
jei sita isimsi - UI pasikeis?

2021-01-23 01:17 UTC, aurimas-darguzis commented on src/components/css/HeaderNav.css
>      /* or display: none - what is the difference */
remove comment

2021-01-23 01:17 UTC, aurimas-darguzis commented on src/components/css/LanguageSelector.css
> +  /* transform: translateY(-4.7vh) translateX(-1rem); */
remove comment

2021-01-23 01:17 UTC, aurimas-darguzis commented on src/components/css/LanguageSelector.css
> +    right: 1rem; */
remove comments

2021-01-25 13:48 UTC, OlegBaras commented on src/components/css/HeaderNav.css
> +  flex-grow: 1;
isemiau, nepasikeite.

2021-01-25 13:54 UTC, aurimas-darguzis commented on src/components/css/HeaderNav.css
> +  flex-grow: 1;
Tai reiskias net ir nereikejo jo cia. Istrink tada. Nereikia kodo, kuris nieko nedaro

2021-01-25 14:05 UTC, OlegBaras reviewed
comments ammended

2021-01-25 14:28 UTC, merged